# Generated by Django 4.2 on 2023-11-26 15:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_payment_amount_to_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expenseid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
